### ISSUE TITLE
Adding blocks to CPTs

### ISSUE THREAD

**Issue by brandslikeus** [ItinerisLtd/acf-gutenblocks#13]
Setting 'post_types' => ['myCPT', anotherCPT'] in a new block has no effect and the block is only available to posts and pages.

Adding 'post_types' to the parent __construct function in Block.php resolves the issue but I wonder if the array should be merged or replaced. i.e. if a block is made available in a CPT should it also be available in all posts and pages by default or should the block be restricted to only the specified CPT?

**Comment by tangrufus** [comment]
Thanks for reporting. 
The array should be replaced like: https://github.com/ItinerisLtd/acf-gutenblocks/blob/51a026d5369771d9d9f514380ae493dedbcd2d59/src/Block.php#L132-L136

**Comment by brandslikeus** [comment]
Thanks for speedy response! 
It looks like this needs to be added to the $settings array on line 128 as well...
'post_types'  => $settings['post_types'],

**Comment by tangrufus** [comment]
good catch
