### ISSUE TITLE
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Itineris\AcfGutenblocks\Util::Itineris\AcfGutenblocks\{closure}() must be of the type string, null given in /dom6319/wp-content/plugins/acf-gutenblocks/src/Util.php:16

### ISSUE THREAD

**Issue by nicksull** [ItinerisLtd/acf-gutenblocks#21]
This has been working perfectly on staging - moved site to live hosting and got the following.

`[27-Jun-2019 12:58:50 UTC] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Itineris\AcfGutenblocks\Util::Itineris\AcfGutenblocks\{closure}() must be of the type string, null given in /dom6319/wp-content/plugins/acf-gutenblocks/src/Util.php:16
Stack trace:
#0 [internal function]: Itineris\AcfGutenblocks\Util::Itineris\AcfGutenblocks\{closure}(NULL)
#1 /dom6319/wp-content/plugins/acf-gutenblocks/src/Util.php(18): array_map(Object(Closure), Array)
#2 /dom6319/wp-content/plugins/acf-gutenblocks/src/AbstractBladeBlock.php(33): Itineris\AcfGutenblocks\Util::sanitizeHtmlClasses(Array)
#3 /dom6319/wp-content/plugins/advanced-custom-fields-pro/pro/blocks.php(303): Itineris\AcfGutenblocks\AbstractBladeBlock->renderBlockCallback(Array, '', false, 180)
#4 /dom6319/wp-content/plugins/advanced-custom-fields-pro/pro/blocks.php(262): acf_render_block(Array, '', false, 180)
#5 /wordpress-5.2.2/wp-includes/class-wp-block-type.php(109): acf_rendered_block(Array, '')
#6 /wordpress-5.2.2/wp-includes/blocks.php(263): WP_ in /dom6319/wp-content/plugins/acf-gutenblocks/src/Util.php on line `

**Comment by codepuncher** [comment]
Hi @nicksull, did you find the issue and resolve it yourself?
Would be good to know the issue and solution.

**Comment by nicksull** [comment]
Hey @codepuncher, running composer require pulls an old version of the code even after composer clearcache. I just downloaded the zip and scp'd it to the server which solved my issue

**Comment by tangrufus** [comment]
This is beacuse the latest commit is not yet tagged.
Until we tag a new release, install the master branch by `$ composer require itinerisltd/acf-gutenblocks:dev-master`
