### ISSUE TITLE
why would you `add` a disabled block?

### ISSUE THREAD

**Issue by tangrufus** [ItinerisLtd/acf-gutenblocks#4]
https://github.com/ItinerisLtd/acf-gutenblocks/blob/b33e2dcb292ca15ab23620bd50fe323308920830/src/Block.php#L120

in other words, why not `remove` it?

**Comment by codepuncher** [comment]
I expect there would be scenarios where you would conditionally enable it.
Don't see us making use of it, but maybe someone will.
